// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {domain} from '../models';

export function AddTask(arg1:string,arg2:time.Time,arg3:string):Promise<domain.Task>;

export function DeleteTask(arg1:number):Promise<Array<domain.Task>>;

export function GetDarkMode():Promise<boolean>;

export function GetTasks():Promise<Array<domain.Task>>;

export function SetDarkMode(arg1:boolean):Promise<boolean>;

export function ToggleTask(arg1:number):Promise<Array<domain.Task>>;
